const ActionType = {
    INCREMENT: 1, // unique range!
    DECREMENT: 2,
    SET_USERS: 3,
    SET_QUESTIONS: 'SET_QUESTIONS',
    ADD_QUESTION: 'ADD_QUESTION',
    SAVE_QUESTION: 'SAVE_QUESTION',
    SET_TAGS: 'SET_TAGS',
    REMOVE_QUESTION: 'REMOVE_QUESTION',
    UPDATE_QUESTION: 'UPDATE_QUESTION',
    GET_QUESTION: 'GET_QUESTION',
    SEARCH_QUESTION: 'SEARCH_QUESTION',
    SET_INTERVIEWS: 'SET_INTERVIEWS',
    REMOVE_INTERVIEW: 'REMOVE_INTERVIEW',
    UPDATE_INTERVIEW: 'UPDATE_INTERVIEW',
    SAVE_INTERVIEW: 'SAVE_INTERVIEW',
    GET_INTERVIEW: 'GET_INTERVIEW',
    SHOW_CONFIRM_DIALOG: 'SHOW_CONFIRM_DIALOG',
    CLOSE_CONFIRM_DIALOG: 'CLOSE_CONFIRM_DIALOG',
    SAVE_TAG: 'SAVE_TAG',
    GET_INTERVIEW_QUESTIONS: 'GET_INTERVIEW_QUESTIONS',
    SAVE_INTERVIEW_QUESTIONS: 'SAVE_INTERVIEW_QUESTIONS',
    REMOVE_INTERVIEW_QUESTION: 'REMOVE_INTERVIEW_QUESTION',
    GET_QUESTION_CHILDREN: 'GET_QUESTION_CHILDREN',
};

export default ActionType;
