const ActionType = {
    INCREMENT: 1, // unique range!
    DECREMENT: 2,
    SET_USERS: 3,
    SET_QUESTIONS: 4,
    ADD_QUESTION: 5,
    SAVE_QUESTION: 6,
    SET_TAGS: 7,
    REMOVE_QUESTION: 8,
    UPDATE_QUESTION: 9,
    GET_QUESTION: 10,
    SEARCH_QUESTION: 11,
    SET_INTERVIEWS: 12,
    REMOVE_INTERVIEW: 13,
    UPDATE_INTERVIEW: 14,
    SAVE_INTERVIEW: 15,
    GET_INTERVIEW: 16,
    SHOW_CONFIRM_DIALOG: 17,
    CLOSE_CONFIRM_DIALOG: 18,
    SAVE_TAG: 19,
    GET_INTERVIEW_QUESTIONS: 20,
    SAVE_INTERVIEW_QUESTIONS: 21,
    REMOVE_INTERVIEW_QUESTION: 22,
    GET_QUESTION_CHILDREN: 23,
};

export default ActionType;
